Update docs to reflect the new certificate flow
Blockstream/greenlight pull request #285
Opened 2023-10-05 09:00 UTC by adi-shankara

- remove all mentions of invite code
- introduce instructions to use the certificate under getting started
- minor fixes with syntax

2023-10-05 09:59 UTC, ErikDeSmedt commented on docs/src/getting-started/certs.md
> +teh build sees the variables.
Typo, should be teh

2023-10-05 09:59 UTC, ErikDeSmedt commented on docs/src/getting-started/register.md
> +	scheduler.register(&signer).await.unwrap();
This will not work. I haven't tested it yet but I think we'll need

````rust
scheduler.register(&signer, None).await.unwrap();
```

2023-10-05 10:32 UTC, cdecker commented
Very good, just two minor typos and a file being renamed that would leave incoming links dangling. Otherwise good to go :+1:

2023-10-05 10:32 UTC, cdecker requested changes

2023-10-05 10:32 UTC, cdecker commented on docs/mkdocs.yml
> -    - reference/partner-certs.md
Don't rename the file, it'll leave any public links dangling. We could use something like `mkdocs-redirect` to put a redirection in place to make it work though

https://github.com/mkdocs/mkdocs-redirects

2023-10-06 11:09 UTC, cdecker commented
I went ahead and set up the redirect. @adi-shankara once the typo and the missing Rust argument to `scheduler.register()` and we should be good to go.

2023-10-06 11:09 UTC, cdecker submitted a review, later dismissed

2023-10-06 11:37 UTC, adi-shankara commented
Typos are now fixed. Thanks for the reviews!

2023-10-06 12:32 UTC, merged