docs: Do not recommend installation from git
Blockstream/greenlight pull request #469
Opened 2024-06-21 13:26 UTC by ErikDeSmedt

Recommend using a tagged installation.

2024-06-21 13:46 UTC, Randy808 submitted a review, later dismissed

2024-06-22 13:32 UTC, cdecker commented
I think that should be 0.2 not 2.0 😋

2024-06-22 13:33 UTC, cdecker requested changes
The correct version is 0.2

2024-06-24 11:37 UTC, cdecker approved these changes

2024-06-24 11:38 UTC, merged