Make onion fields optional
Blockstream/greenlight pull request #544
Opened 2024-11-21 14:20 UTC by nepet

This PR makes all of the onion payload fields for the lsp clients `htlc_accepted` hook handler optional. We can not assume that all fields are set and we need to act to what we get. If the handler processes an onion payload that is missing essential fields it will stop executing and return the `continue` signal to core-lightning to pass the htlc to the next processor/handler in line.

Resolves #541

2024-11-22 10:44 UTC, cdecker requested changes
All good changes, let's just reflect the `shared_secret` and `next_onion` having the correct optionality (they're not optional), and the other things are suggestions, so feel free to drop them.

2024-11-22 10:44 UTC, cdecker commented on libs/gl-plugin/src/lsp.rs
> +                "lsp-plugin: got an onion payload={} without an amt forward_msat.",
Add the outcome `continuing` so we don't spook people reading the logs, thinking that it is not being handled.

2024-11-22 10:44 UTC, cdecker commented on libs/gl-testing/tests/test_node.py
> -    """Register and schedule a node, then connect to it.
Feels like the changes here should have been a separate format commit. Are there any logic changes in here?

2024-11-25 12:43 UTC, nepet commented on libs/gl-plugin/src/lsp.rs
> +macro_rules! unwrap_or_continue {
This is what i considered to do first, but I fail to see how this is possible. How can we return an outer function from an inner function without calling panic (like unwrap does)? I also explored the possibility of using a [ControlFlow](https://doc.rust-lang.org/std/ops/enum.ControlFlow.html) or a custom implementation of the [Try](https://doc.rust-lang.org/std/ops/trait.Try.html) trait, using the ?-operator, but that also seemed a bit overly complicated given that we only use this in one place for now (the try trait is experimental as well).
I would suggest to leave it as is for now and If we feel that we could profit from this pattern at other places as well, we can move it upstream to the cln-plugin repo and may come up with a solution that is a bit more aligned with the chaining approach that rust follows.

2024-11-25 13:03 UTC, nepet commented
Made `shared_secret` and `next_onion` optional and rebased on `main`.

2024-11-25 13:39 UTC, merged